export const Nfts = [
    {
      id: "0",
      url: "https://nft-marketplace-1n1h5ebmp-namyakhan.vercel.app/images/nfts/nft1.png",
      title: "Classic Jester #1672",
      profile: "https://nft-marketplace-1n1h5ebmp-namyakhan.vercel.app/images/nfts/larvartist.svg",
      artist: "@larvartist",
      price: "ETH 6",
    },
    {
      id: "1",
      url: "https://nft-marketplace-1n1h5ebmp-namyakhan.vercel.app/images/nfts/nft2.png",
      title: "Bored Ape #1789",
      profile: "https://nft-marketplace-1n1h5ebmp-namyakhan.vercel.app/images/nfts/apecreator.svg",
      artist: "@apecreator",
      price: "ETH 6",
    },
    {
      id: "2",
      url: "https://nft-marketplace-1n1h5ebmp-namyakhan.vercel.app/images/nfts/nft3.png",
      title: "Teddy Bear #1223",
      profile: "https://nft-marketplace-1n1h5ebmp-namyakhan.vercel.app/images/nfts/larvartist.svg",
      artist: "@larvartist",
      price: "ETH 2",
    },
    {
      id: "3",
      url: "https://nft-marketplace-1n1h5ebmp-namyakhan.vercel.app/images/nfts/nft4.png",
      title: "Gold Monkey #1834",
      profile: "https://nft-marketplace-1n1h5ebmp-namyakhan.vercel.app/images/nfts/apecreator.svg",
      artist: "@apecreator",
      price: "ETH 16",
    },
    {
      id: "4",
      url: "https://nft-marketplace-1n1h5ebmp-namyakhan.vercel.app/images/nfts/nft1.png",
      title: "Mr. Noir #563",
      profile: "https://nft-marketplace-1n1h5ebmp-namyakhan.vercel.app/images/nfts/larvartist.svg",
      artist: "@hypebeast",
      price: "ETH 2.3",
    },
    {
      id: "5",
      url: "https://nft-marketplace-1n1h5ebmp-namyakhan.vercel.app/images/nfts/nft5.png",
      title: "Epic Hero #2893",
      profile: "https://nft-marketplace-1n1h5ebmp-namyakhan.vercel.app/images/nfts/hypebeast.svg",
      artist: "@nftartist",
      price: "ETH 9",
    },
    {
      id: "6",
      url: "https://nft-marketplace-1n1h5ebmp-namyakhan.vercel.app/images/nfts/nft6.png",
      title: "Lion Legends #1223",
      profile: "https://nft-marketplace-1n1h5ebmp-namyakhan.vercel.app/images/nfts/nftartist.svg",
      artist: "@hypebeast",
      price: "ETH 4.3",
    },
    {
      id: "7",
      url: "https://nft-marketplace-1n1h5ebmp-namyakhan.vercel.app/images/nfts/nft8.png",
      title: "Ayomi #1273",
      profile: "https://nft-marketplace-1n1h5ebmp-namyakhan.vercel.app/images/nfts/larvartist.svg",
      artist: "@larvartist",
      price: "ETH 2.1",
    },
    {
      id: "8",
      url: "https://nft-marketplace-1n1h5ebmp-namyakhan.vercel.app/images/nfts/nft9.png",
      title: "Big Cats #136",
      profile: "https://nft-marketplace-1n1h5ebmp-namyakhan.vercel.app/images/nfts/hypebeast.svg",
      artist: "@hypebeast",
      price: "ETH 2.1",
    },
    {
      id: "9",
      url: "https://nft-marketplace-1n1h5ebmp-namyakhan.vercel.app/images/nfts/nft10.png",
      title: "Bored Ape #1703",
      profile: "https://nft-marketplace-1n1h5ebmp-namyakhan.vercel.app/images/nfts/apecreator.svg",
      artist: "@apecreator",
      price: "ETH 2.1",
    },
    {
      id: "10",
      url: "https://nft-marketplace-1n1h5ebmp-namyakhan.vercel.app/images/nfts/nft11.png",
      title: "Classic Jester #23",
      profile: "https://nft-marketplace-1n1h5ebmp-namyakhan.vercel.app/images/nfts/larvartist.svg",
      artist: "@larvartist",
      price: "ETH 2.1",
    },
    {
      id: "11",
      url: "https://nft-marketplace-1n1h5ebmp-namyakhan.vercel.app/images/nfts/nft12.png",
      title: "Crypto Pioneer #023",
      profile: "https://nft-marketplace-1n1h5ebmp-namyakhan.vercel.app/images/nfts/nftartist.svg",
      artist: "@nftartist",
      price: "ETH 2.1",
    },
    {
      id: "12",
      url: "https://nft-marketplace-1n1h5ebmp-namyakhan.vercel.app/images/nfts/nft13.png",
      title: "Classic Jester #23",
      profile: "https://nft-marketplace-1n1h5ebmp-namyakhan.vercel.app/images/nfts/larvartist.svg",
      artist: "@larvartist",
      price: "ETH 2.1",
    },
    {
      id: "13",
      url: "https://nft-marketplace-1n1h5ebmp-namyakhan.vercel.app/images/nfts/nft14.png",
      title: "Floating in Space #136",
      profile: "https://nft-marketplace-1n1h5ebmp-namyakhan.vercel.app/images/nfts/nftartist.svg",
      artist: "@nftartist",
      price: "ETH 2.1",
    },
    {
      id: "14",
      url: "https://nft-marketplace-1n1h5ebmp-namyakhan.vercel.app/images/nfts/nft15.png",
      title: "Bored Ape #136",
      profile: "https://nft-marketplace-1n1h5ebmp-namyakhan.vercel.app/images/nfts/apecreator.svg",
      artist: "@apecreator",
      price: "ETH 2.1",
    },
    {
      id: "15",
      url: "https://nft-marketplace-1n1h5ebmp-namyakhan.vercel.app/images/nfts/nft16.png",
      title: "Big Cats #136",
      profile: "https://nft-marketplace-1n1h5ebmp-namyakhan.vercel.app/images/nfts/hypebeast.svg",
      artist: "@hypebeast",
      price: "ETH 2.1",
    },
  ];